export const itineraryData = [
  {
    id: 1,
    day: 1,
    title: "Burj Khalifa",
    description: "Visit the world's tallest building and enjoy breathtaking views from the observation deck on the 124th and 125th floors.",
    icon: "🏙️",
    tips: "Book tickets in advance for sunset views. Wear comfortable shoes as there's considerable walking involved.",
  },
  {
    id: 2,
    day: 2,
    title: "Desert Safari",
    description: "Experience thrilling dune bashing, camel riding, sandboarding, and a traditional Bedouin camp with BBQ dinner and cultural show.",
    icon: "🐪",
    tips: "Wear light, breathable clothing. Bring a scarf for sand protection. Evening safaris offer the best experience.",
  },
  {
    id: 3,
    day: 3,
    title: "Dubai Marina",
    description: "Stroll along the picturesque marina walk, admire luxury yachts, and enjoy waterfront dining with skyline views.",
    icon: "⛵",
    tips: "Visit during sunset for the best photos. Try the marina walk at night when the lights are on.",
  },
  {
    id: 4,
    day: 4,
    title: "Al Fahidi & Gold Souk",
    description: "Explore the historic Al Fahidi neighborhood with its wind-tower architecture, then visit the famous Gold Souk in Deira.",
    icon: "🕌",
    tips: "Best visited in the morning to avoid heat. Haggling is expected in the souks. Wear modest clothing.",
  },
  {
    id: 5,
    day: 5,
    title: "Palm Jumeirah",
    description: "Visit the iconic palm-shaped island, see Atlantis The Palm, and enjoy beach time or a monorail ride.",
    icon: "🌴",
    tips: "The monorail offers great views. Public beach access is available at The Beach opposite JBR.",
  },
  {
    id: 6,
    day: 6,
    title: "Dubai Frame",
    description: "Walk through this architectural landmark that frames old Dubai on one side and modern Dubai on the other.",
    icon: "🖼️",
    tips: "Go early to avoid crowds. The glass floor walkway offers thrilling views downward.",
  },
  {
    id: 7,
    day: 7,
    title: "Abu Dhabi Day Trip",
    description: "Visit the capital city to see the magnificent Sheikh Zayed Grand Mosque, Louvre Abu Dhabi, and Emirates Palace.",
    icon: "🕌",
    tips: "Leave early (around 7 AM) to maximize your day. Dress modestly for mosque visit (scarf and long clothing provided if needed).",
  },
  {
    id: 8,
    day: 8,
    title: "Ski Dubai",
    description: "Experience real snow in the desert! Ski, snowboard, or just play in the snow at this indoor winter wonderland.",
    icon: "❄️",
    tips: "Bring socks (gloves and jacket provided). Allow 3-4 hours for the full experience. Best on hot days!",
  },
  {
    id: 9,
    day: 9,
    title: "Creek Dhow Cruise",
    description: "Take a traditional wooden dhow cruise along Dubai Creek, seeing old Dubai's sights with dinner and entertainment.",
    icon: "🚤",
    tips: "Evening cruises offer the best atmosphere. Try the local cuisine options on board.",
  },
  {
    id: 10,
    day: 10,
    title: "Bluewaters Island",
    description: "Visit the newest island destination featuring Ain Dubai (world's largest observation wheel), beaches, and dining.",
    icon: "🎡",
    tips: "Combine with JBR Beach visit. Ain Dubai offers stunning panoramic views - book sunset slots for best photos.",
  },
];